FROM mongo:7.0
COPY *.js /docker-entrypoint-initdb.d
# copy the .js files placed above loaction and docker run this files
#docker build -t mongodb:1 . where will be dockerfile we run that dirtcory 
#docker run -d --name mongodb mpngodb:1 
#docker ps 